services:
  discord-bot:
    image: bun-server
    container_name: esports-discord-bot
    restart: unless-stopped
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - CLIENT_ID=${CLIENT_ID}
      - SCRIPT_LINK=${SCRIPT_LINK}
    build:
      context: .
      dockerfile: Dockerfile
    